# Generated by Django 4.0.3 on 2022-09-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_automobilevo_color_automobilevo_is_sold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='employee_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
