# Generated by Django 4.0.3 on 2022-09-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_rest', '0003_alter_automobile_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='picture_url',
            field=models.URLField(null=True),
        ),
    ]
